name: Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            if [ ! -d "${{ secrets.VM_APP_PATH }}" ]; then
              git clone https://github.com/Adrien137/github-actions-tp1.git ${{ secrets.VM_APP_PATH }}
            fi

            cd ${{ secrets.VM_APP_PATH }}
            git pull origin main

            docker stop task-api || true
            docker rm task-api || true

            docker build -t task-api:latest .
            docker run -d \
              --name task-api \
              -p 80:5000 \
              --restart unless-stopped \
              task-api:latest