name: Deploy Azure

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            if [ ! -d "github-actions-tp1" ]; then
              git clone https://github.com/Adrien137/github-actions-tp1.git github-actions-tp1
            fi

            cd github-actions-tp1
            git pull origin main

            sudo apt-get install -y docker-compose

            sudo docker-compose down
            sudo docker-compose up -d --build
